# -*- coding: utf-8 -*-
"""1.1 - Análise Exploratória Dados - AndreLF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-iMzztmvMWpjsXZIEZSSyb9ADWu_lAQ
"""

import pandas as pd

df_BLI = pd.read_csv('OECD,DF_BLI,+all.csv', sep = ",") # data frame = representacao estruturada do dado. usa pandas para ler
df_BLI # exibe conteúdo do data frame (apenas no notebook do google)

df_BLI.head() # visualiza as 5 primeiras linhas de df_BLI

df_BLI["INEQUALITY"].value_counts() # conta quantas vezes cada valor aparece na coluna inequality (nn aparece acima)

df_BLI.columns # mostra colunas (agora aparece o inequality)

df_BLI.describe() # resumo estatístico

df_BLI.info() # resumo estrutural

# Filtrando (Where)
# Necessário conhecimento do domínio
df_BLI = df_BLI [ df_BLI['INEQUALITY'] == 'TOT'] # apenas linhas que coluna INEQUALITY tem TOT
df_BLI = df_BLI [ df_BLI['Indicator'] == 'Life satisfaction' ] #  "  "
df_BLI

df_BLI = df_BLI[['LOCATION','Country','OBS_VALUE']] # Seleciona apenas 3 colunas do DataFrame
df_BLI

df_BLI.describe() # estatistico

df_BLI.sort_values("OBS_VALUE",ascending=False, inplace = True) # ordena df por obs_value. decrescente. altera o df original (nn faz copia)
df_BLI

#GDP Per Capta
#https://data.worldbank.org/indicator/NY.GDP.PCAP.CD?most_recent_value_desc=true -- 14/03/2023
#https://www.kaggle.com/datasets/nitishabharathi/gdp-per-capita-all-countries?resource=download

df_GDP = pd.read_csv("GDP.csv", sep = ",")
df_GDP

df_GDP.columns

df_GDP = df_GDP[['Country Code','Country ','2018']] # cria df só com esses columns
df_GDP

df_GDP.describe() # estatistico

df_GDP.info() # estrutural

#Junção de ambos DFs por código de páis
df = df_BLI.set_index('LOCATION').join(df_GDP.set_index('Country Code'), how = 'inner') # intersecção (aparece em ambos)
df

df[['OBS_VALUE']].plot() # plota o gráfico

df[['2018']].plot()

df.plot(kind = 'scatter', x = 'OBS_VALUE', y = '2018') # scatter = disperso

pd.plotting.scatter_matrix(df, figsize=(15,15)) #  Mostra gráficos de dispersão e histogramas para explorar relações entre colunas numéricas.

df[['2018', 'OBS_VALUE']].corr() # calcula matriz de correção (de -1 até 1), no caso, uns 70%. correlação linear

"""Com base nos valores obtidos, pode-se afirmar que existe significativa correlação entre o GDP de 2018 e os valores de BLI por país.

# Exercício
Baixe a base de dados de QI por país e investigue:
1.   qual o QI médio a nível mundial?
2.   qual o QI médio por continente?
3.   plote o gráfico de QI por país
4.   existe alguma correlação aparente entre QI e BLI ou GDP, investigados nos exemplos anteriores? Use JOIN.

QI - arquivo CSV:<br>
**https://worldpopulationreview.com/country-rankings/average-iq-by-country**
"""

df_qi = pd.read_csv('qi-médio-por-país-em-2025.csv', sep = ",")
df_qi

df_qi.head()

df_qi.columns

df_qi.describe() # estatistico

df_qi.info() # estrutural

respostas = df_qi[[ # qi medio mundial
    'CountriesByIQ_AverageIQViaInternationalIQTest_avgIQ_2024',
    'CountriesByIQ_AverageIQViaLynnBecker_avgIQ_2019',
    'CountriesByIQ_LynnBeckerDataSource_testOrEstimate_2019',
    'CountriesByIQ_ICI2017Score',
    'CountriesByIQ_ICI2017Grade'
]].mean(numeric_only=True)

print(f"QI médio mundial:\n {respostas}")

df_qi.plot(kind = 'scatter', x = 'flagCode', y = 'CountriesByIQ_AverageIQViaInternationalIQTest_avgIQ_2024') # grafico plotado para cada flag code (contiente)

"""Existe correlação entre BLI e o QI."""

df_corr_GDP = df_GDP.set_index('Country ').join(df_qi.set_index('country'), how = 'inner') # correlacao
df_corr_GDP