# -*- coding: utf-8 -*-
"""1.2 - Árvore de Decisão e Classificação - AndreLF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13UEkngPMuWuUvHv9M5G7iwfQqhfcT0qV

https://www.kaggle.com/competitions/digit-recognizer
"""

#Abrindo o arquivo  https://docs.google.com/presentation/d/1qgQa_IJUXAqrq2xunpaw733B3MxeHh0N/edit?slide=id.p20#slide=id.p20

import pandas as pd

df = pd.read_csv("train.csv")
df

df.columns

df.iloc[0] # primeiro digito.  integer location

# separa entrada (x) do rótulo (y). remove label (resposta que o modelo deve aprender a prever.)
x = df.drop("label", axis=1) # axis = 1: remove uma coluna, se fosse 0, seria linha.
y = df['label'] # fica apenas label

x # features

y # label

# Pega a primeira linha de x (features) e converte essa linha em uma lista simples de valores (cada valor é a intensidade de um pixel)

image0 = x.iloc[0].to_list() # LISTA

# imagem 28x28 pixels
for i in range(28):
    for j in range(28):

        # Calcula o índice do pixel na lista
        pixel = image0[i*28 + j]

        # Define o espaço a ser usado após o número do pixel para deixar a saída alinhada:
        if pixel < 10: space = '   '
        elif pixel < 100: space = '  '
        else: space = ' '

        # Imprime o valor do pixel e o espaço definido, sem pular linha (end=space)
        print(pixel, end=space)

    # Após imprimir todos os pixels da linha, pula para a próxima linha
    print()

# Imprime rótulo da imagem (qual dígito ela representa). Pega o valor da coluna 'label' da primeira linha do DataFrame original
print('Classe:', df.iloc[0]['label'])

from matplotlib import pyplot as plt
import numpy as np

first_image = np.array(image0, dtype='float') # converte para array numpy do tipo float
pixels = first_image.reshape((28, 28)) # reorganiza em 28x28. oranizados em imagem e não só em uma unica linha (pois image0 era uma lista)
plt.imshow(pixels, cmap='gray')
plt.show()

#dividindo entre conjunto de treino e testes

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42) # hold out, 42 fixa semente do gerador aleatorio (numero arbitrario)

from sklearn.preprocessing import StandardScaler  # Importa a classe para padronização dos dados

scaler = StandardScaler()  # Cria um objeto StandardScaler

X_train_scaled = scaler.fit_transform(X_train)  # X_train_scaled é o conjunto X_train com dados normalizados (média 0 e desvio padrão 1)

X_train_scaled

X_train_scaled[0] # acessa primeiro exemplo

# treinando os modelos

# from sklearn.linear_model import LogisticRegression
# clf = LogisticRegression().fit(X_train_scaled, y_train)  ->   Acuracia 0.9091666666666667

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train_scaled, y_train)  # Acuracia 0.7906618778860954. Y não é scaled.

acc = clf.score(scaler.transform(X_test), y_test) #score. normaliza internamente o X

print('Acuracia', acc)
# Imprime o valor da acurácia na tela.

# prevendo dados do conjunto de testes

pred = clf.predict(scaler.transform(X_test[:1])) # Faz a previsão da classe do primeiro exemplo do teste, após normalizar seus dados.
pred

"""TITANIC"""

#Abrindo o arquivo

import pandas as pd

df = pd.read_csv("trainTitanic.csv")
df

df.columns

df.Survived

df.info()

df.describe()

df.head()

df = df.dropna()  # remove valores ausentes

x = df.drop(["Survived", "Name", "Sex", "Ticket", "Cabin", "Embarked"], axis=1) # 1 = coluna
y = df["Survived"] # LABEL

#dividindo entre conjunto de treino e testes

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

# normalizando os dados
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train_scaled, y_train)

# medindo a acutácia (media dos acertos)

acc = clf.score(scaler.transform(X_test),y_test)
print('Acuracia',acc)

a
pred = clf.predict(scaler.transform(X_test[:1]))
pred

df.plot(kind = 'scatter', x = 'Survived', y = 'Fare')  # qual gráfico plotar?