# -*- coding: utf-8 -*-
"""1.3 - Regressão Linear - AndreLF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18N59Eeghw-Dea8wHdgsZBrWyPoW1cez2
"""

#
# Linear Regression: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html
#
# New Dataset: https://www.kaggle.com/datasets/yashpaloswal/ann-car-sales-price-prediction?select=car_purchasing.csv
#

import pandas as pd
df = pd.read_csv('car_purchasing.csv', encoding="latin-1") # erro no utf-8
df

df.info()

df.describe()

df.plot(x = 'annual Salary', y = 'car purchase amount', kind = 'scatter') # relaciona salario e carro

df.select_dtypes(include=['float64', 'int64']).corr()['car purchase amount'].sort_values(ascending=False)
# seleciona apenas numeros
# faz correlacao de todas as colunas numéricas e a coluna "car purchase amount"
# Ordena as correlações da coluna "car purchase amount" em ordem decrescente

# x = df.drop('car purchase amount', axis = 1) # Se for usar todas as características (features)

# Usando a característica que possui maior correlação com preço
# Equação final: y = a*X + b --> y = net_sqm*X + b

x = df[['annual Salary']]
y = df['car purchase amount']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train) # x não normaliza?
# car_purchase_amount=a⋅annual_salary+b

lr.coef_ # coeficiente angular. f(x) = 0.57 X + B

lr.intercept_ #  # intercepto. f(x) = 0.57 X + 8237

# retorna R^2, o quanto consegue explicar prever (no caso, uns 30%)
lr.score(x_test, y_test)

# Mean Squared Error
y_pred = lr.predict(x_test) # Usa lr para prever o valor da compra do carro (y_pred) com base no teste (x_test).

from sklearn.metrics import root_mean_squared_error

root_mean_squared_error(y_test, y_pred)

import matplotlib.pyplot as plt

plt.scatter(x_test['annual Salary'], y_test, color ='b')  # plota os pontos reais (dados de teste) em azul
plt.scatter(x_test['annual Salary'], y_pred, color ='k')     # plota a reta da regressão (valores previstos) em preto

plt.show()

