# -*- coding: utf-8 -*-
"""1.4 - Redes Neurais - AndreLF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-UlvuealKruyqk3FYAA6Frfc5mMgjdr

https://www.kaggle.com/competitions/titanic/leaderboard#
"""

import pandas as pd

df = pd.read_csv("./data.csv")
df.head()

df.describe()

df.dtypes

df.columns

X = df.drop(['diagnosis', 'Unnamed: 32'],axis=1)
y = df['diagnosis']

X

X.describe()

y

y.describe()

#Separar 80% / 20%
#### Cross Validation
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### Normalize data
from sklearn.preprocessing import MinMaxScaler # cada coluna foi normalizada entre 0 e 1. mantem proporcao de atributos
scaler = MinMaxScaler()
X_train_norm = scaler.fit_transform(X_train)

## Treinando a RNA do tipo MLP
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(10, 100, 10), max_iter=1000) # RNA com 3 camandas, sendo: 10 neurônios na primeira camada, 100 na segunda, 10 na terceira
clf = clf.fit(X_train, y_train) # drop off no Nan

from sklearn.metrics import accuracy_score
predicted = clf.predict(scaler.transform(X_test))
accuracy = accuracy_score(y_test, predicted)

print("MLP: ",accuracy)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predicted)

print(predicted[0], y_test.iloc[0])

print(predicted[1], y_test.iloc[1])

print(predicted[2], y_test.iloc[2])

